name: On Push Run

on: push

env:
  DEVOPS_DIR: G-Aactions-Devops

jobs:
  hello-world:
    name: Hello world
    runs-on: ubuntu-latest
    steps:
    - name: Check-out devops repository
      uses: actions/checkout@v2
      with:
        repository: saidinkar/G-Aactions-Devops

    - name: Hello World
      run: python ${{ env.DEVOPS_DIR }}/hello_world.py
      shell: sh
