name: On Push Run

on: push

env:
  DEVOPS_DIR: G-Aactions-Devops

jobs:
  hello-world:
    name: Hello world
    runs-on: ubuntu-latest
    steps:
    - name: Check-out devops repository
      uses: actions/checkout@v2
      with:
        repository: saidinkar/G-Aactions-Devops
        token: ${{ secrets.GITHUB_TOKEN }}
        path: ${{ env.DEVOPS_DIR }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Hello World
      run: python ${{ env.DEVOPS_DIR }}/main.py
      shell: sh
